platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

pod 'Fakery'
pod 'Wall', path: '../../'
pod 'Imaginary', git: 'https://github.com/hyperoslo/Imaginary'
pod 'Cache', git: 'https://github.com/hyperoslo/Cache'
